In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [60]:
df = pd.read_csv('Cars_24.csv')

In [61]:
df.head()

selling_price    year  km_driven  mileage  engine  max_power   age  \
0           1.20  2012.0     120000    19.70   796.0      46.30  11.0   
1           5.50  2016.0      20000    18.90  1197.0      82.00   7.0   
2           2.15  2010.0      60000    17.00  1197.0      80.00  13.0   
3           2.26  2012.0      37000    20.92   998.0      67.10  11.0   
4           5.70  2015.0      30000    22.77  1498.0      98.59   8.0   

      make                                      model  Individual  \
0   MARUTI                                   ALTO STD           1   
1  HYUNDAI                             GRAND I10 ASTA           1   
2  HYUNDAI                                   I20 ASTA           1   
3   MARUTI                     ALTO K10 2010-2014 VXI           1   
4     FORD  ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV           0   

   Trustmark Dealer  Diesel  Electric  LPG  Petrol  Manual  5  >5  
0                 0       0         0    0       1       1  1   0  
1                 0       0         0    0       1       1  1   0  
2                 0       0         0    0       1       1  1   0  
3                 0       0         0    0       1       1  1   0  
4                 0       1         0    0       0       1  1   0

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19820 entries, 0 to 19819
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   selling_price     19820 non-null  float64
 1   year              19820 non-null  float64
 2   km_driven         19820 non-null  int64  
 3   mileage           19820 non-null  float64
 4   engine            19820 non-null  float64
 5   max_power         19820 non-null  float64
 6   age               19820 non-null  float64
 7   make              19820 non-null  object 
 8   model             19820 non-null  object 
 9   Individual        19820 non-null  int64  
 10  Trustmark Dealer  19820 non-null  int64  
 11  Diesel            19820 non-null  int64  
 12  Electric          19820 non-null  int64  
 13  LPG               19820 non-null  int64  
 14  Petrol            19820 non-null  int64  
 15  Manual            19820 non-null  int64  
 16  5                 19820 non-null  int64 

In [63]:
df.isnull().sum()

selling_price       0
year                0
km_driven           0
mileage             0
engine              0
max_power           0
age                 0
make                0
model               0
Individual          0
Trustmark Dealer    0
Diesel              0
Electric            0
LPG                 0
Petrol              0
Manual              0
5                   0
>5                  0
dtype: int64

Visualizing Categorical Attributes

In [64]:
df['make'].head()

0     MARUTI
1    HYUNDAI
2    HYUNDAI
3     MARUTI
4       FORD
Name: make, dtype: object

In [65]:
df['model'].head()

0                                     ALTO STD
1                               GRAND I10 ASTA
2                                     I20 ASTA
3                       ALTO K10 2010-2014 VXI
4    ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV
Name: model, dtype: object

In [66]:
df['make'].nunique() #nunique() will return the number of unique values in the column 'make' of the DataFrame df.

41

In [67]:
df['model'].nunique()

3233

Converting Categorical column into Numerical one
Applying Target Encoding

In [68]:
from category_encoders import TargetEncoder

In [69]:
encoder_1 = TargetEncoder(cols=['make'])

df['make'] = encoder_1.fit_transform(df['make'], df['selling_price'])

In [70]:
encoder_2 = TargetEncoder(cols=['model'])

df['model'] = encoder_2.fit_transform(df['model'], df['selling_price'])

In [71]:
df.head()

selling_price    year  km_driven  mileage  engine  max_power   age  \
0           1.20  2012.0     120000    19.70   796.0      46.30  11.0   
1           5.50  2016.0      20000    18.90  1197.0      82.00   7.0   
2           2.15  2010.0      60000    17.00  1197.0      80.00  13.0   
3           2.26  2012.0      37000    20.92   998.0      67.10  11.0   
4           5.70  2015.0      30000    22.77  1498.0      98.59   8.0   

       make     model  Individual  Trustmark Dealer  Diesel  Electric  LPG  \
0  4.684721  5.235537           1                 0       0         0    0   
1  5.458819  5.527772           1                 0       0         0    0   
2  5.458819  5.380584           1                 0       0         0    0   
3  4.684721  2.268993           1                 0       0         0    0   
4  5.858258  6.736442           0                 0       1         0    0   

   Petrol  Manual  5  >5  
0       1       1  1   0  
1       1       1  1   0  
2       1       1  1   0  
3       1       1  1   0  
4       0       1  1   0

Dividing the dataset into input and output

In [72]:
x = df.drop('selling_price', axis=1)
y = df['selling_price']

In [73]:
x.head()

year  km_driven  mileage  engine  max_power   age      make     model  \
0  2012.0     120000    19.70   796.0      46.30  11.0  4.684721  5.235537   
1  2016.0      20000    18.90  1197.0      82.00   7.0  5.458819  5.527772   
2  2010.0      60000    17.00  1197.0      80.00  13.0  5.458819  5.380584   
3  2012.0      37000    20.92   998.0      67.10  11.0  4.684721  2.268993   
4  2015.0      30000    22.77  1498.0      98.59   8.0  5.858258  6.736442   

   Individual  Trustmark Dealer  Diesel  Electric  LPG  Petrol  Manual  5  >5  
0           1                 0       0         0    0       1       1  1   0  
1           1                 0       0         0    0       1       1  1   0  
2           1                 0       0         0    0       1       1  1   0  
3           1                 0       0         0    0       1       1  1   0  
4           0                 0       1         0    0       0       1  1   0

In [74]:
y.head()

0    1.20
1    5.50
2    2.15
3    2.26
4    5.70
Name: selling_price, dtype: float64

 # Splitting the Dataset into train and test data

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [77]:
x_train.shape, y_train.shape

((14865, 17), (14865,))

In [78]:
x_test.shape, y_test.shape

((4955, 17), (4955,))

In [79]:
from sklearn.preprocessing import StandardScaler

In [80]:
scaler = StandardScaler()
scaled_train = scaler.fit_transform(x_train)
scaled_train

array([[-1.11516895, -0.81076741,  2.0710607 , ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 1.07946178, -0.96876242,  1.41987737, ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 0.7659431 , -0.19826591, -0.975547  , ...,  0.49894865,
        -2.2521776 ,  2.35858303],
       ...,
       [-0.17461292,  0.99333244, -0.04528511, ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 0.45242443,  0.28014297, -0.39413331, ...,  0.49894865,
         0.44401472, -0.42398338],
       [-0.17461292,  0.72404123, -1.73138478, ...,  0.49894865,
        -2.2521776 ,  2.35858303]])

In [81]:
scaled_test = scaler.transform(x_test)
scaled_test

array([[ 0.7659431 ,  0.49833408,  0.4989181 , ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 0.13890575,  0.08077584,  0.15006989, ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 0.45242443,  0.30422592,  1.81523868, ...,  0.49894865,
         0.44401472, -0.42398338],
       ...,
       [ 0.7659431 , -0.40449454,  1.03614434, ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 0.45242443, -0.51734812, -0.95229045, ...,  0.49894865,
        -2.2521776 ,  2.35858303],
       [-0.17461292, -0.0201604 ,  0.39891495, ...,  0.49894865,
         0.44401472, -0.42398338]])

In [82]:
x_train[x_train.columns] = scaled_train

In [83]:
x_train.head()

year  km_driven   mileage    engine  max_power       age      make  \
18869 -1.115169  -0.810767  2.071061 -0.441997  -0.545491  1.115169 -0.526860   
3198   1.079462  -0.968762  1.419877  0.043501  -0.009973 -1.079462 -0.159551   
14770  0.765943  -0.198266 -0.975547  2.874926  -0.325906 -0.765943 -0.612940   
16545  0.452424  -0.517348  0.073323 -0.756600  -0.678810 -0.452424 -0.307328   
7508  -2.369244   2.191138 -2.184887  1.705847   1.202222  2.369244 -0.159551   

          model  Individual  Trustmark Dealer    Diesel  Electric       LPG  \
18869 -0.880032   -0.799437         -0.100623  1.013069 -0.020095 -0.053862   
3198   0.349767    1.250880         -0.100623  1.013069 -0.020095 -0.053862   
14770 -0.133186   -0.799437         -0.100623  1.013069 -0.020095 -0.053862   
16545 -1.126174    1.250880         -0.100623 -0.987100 -0.020095 -0.053862   
7508   0.227251   -0.799437         -0.100623 -0.987100 -0.020095 -0.053862   

         Petrol    Manual         5        >5  
18869 -0.972330  0.498949  0.444015 -0.423983  
3198  -0.972330  0.498949  0.444015 -0.423983  
14770 -0.972330  0.498949 -2.252178  2.358583  
16545  1.028457  0.498949  0.444015 -0.423983  
7508   1.028457 -2.004214  0.444015 -0.423983

In [84]:
x_test[x_test.columns] = scaled_test

In [85]:
x_test.head()

year  km_driven   mileage    engine  max_power       age      make  \
960    0.765943   0.498334  0.498918 -0.028353  -0.303500 -0.765943 -0.549001   
4073   0.138906   0.080776  0.150070  0.043501  -0.213873 -0.138906 -0.284219   
4339   0.452424   0.304226  1.815239  0.043501   0.005711 -0.452424 -0.159551   
19325  0.452424  -0.620903 -0.184824 -0.537155  -0.216114 -0.452424 -0.159551   
438   -0.801650   0.046920  0.331471 -0.927496  -0.700096  0.801650 -0.526860   

          model  Individual  Trustmark Dealer    Diesel  Electric       LPG  \
960   -0.041712    1.250880         -0.100623  1.013069 -0.020095 -0.053862   
4073  -0.444664   -0.799437         -0.100623  1.013069 -0.020095 -0.053862   
4339   0.074281   -0.799437         -0.100623  1.013069 -0.020095 -0.053862   
19325  0.058142   -0.799437         -0.100623 -0.987100 -0.020095 -0.053862   
438   -1.956766    1.250880         -0.100623 -0.987100 -0.020095 -0.053862   

         Petrol    Manual         5        >5  
960   -0.972330  0.498949  0.444015 -0.423983  
4073  -0.972330  0.498949  0.444015 -0.423983  
4339  -0.972330  0.498949  0.444015 -0.423983  
19325  1.028457  0.498949  0.444015 -0.423983  
438    1.028457  0.498949  0.444015 -0.423983

Modeling

In [86]:
from sklearn.linear_model import LinearRegression

In [87]:
model = LinearRegression()

In [88]:
model.fit(x_train, y_train)

LinearRegression()

In [89]:
pred_train = model.predict(x_train)

In [90]:
pred_train

array([2.43069487, 8.21501748, 7.25335759, ..., 4.23677639, 7.59682523,
       7.91456044])

In [91]:
model.coef_

array([ 0.7086768 , -0.23304777, -0.20822646,  0.11395199,  1.24120716,
       -0.7086768 ,  1.50379923,  1.18319752, -0.11028765, -0.03662805,
        0.19601818,  0.07803259, -0.00200932, -0.20187893, -0.43030697,
       -0.09287471,  0.00347571])

In [92]:
model.intercept_

6.586707923309764

In [93]:
pred_test = model.predict(x_test)

In [94]:
pred_test

array([6.1991489 , 5.74733031, 6.86693006, ..., 3.18760594, 9.8529386 ,
       4.34662333])

In [95]:
from sklearn.metrics import mean_squared_error

In [96]:
train_mse = mean_squared_error(y_train, pred_train, squared=False)
train_mse

1.8360675074925843

In [97]:
test_mse = mean_squared_error(y_test, pred_test, squared=False)
test_mse

1.840268665386834

# R2 Score --

Linear Regression by default calculates R2 score using .score() method

In [98]:
train_r2 = model.score(x_train, y_train)
train_r2

0.8564559762707435

In [99]:
test_r2 = model.score(x_test, y_test)
test_r2

0.8560598088397423

# Adjusted R2 Score -

In [100]:
def adjusted_r2(r2,m,d):
    return (1 - (((1-r2)*(m-1))/(m-d-1)))

In [101]:
m1 = x_train.shape[0]
d1 = x_train.shape[1]

m1,d1

(14865, 17)

In [102]:
train_adj = adjusted_r2(train_r2, m1, d1)
train_adj

0.8562916165749533

In [103]:
m2 = x_test.shape[0]
d2 = x_test.shape[1]

m2,d2

(4955, 17)

In [104]:
test_adj = adjusted_r2(test_r2, m2, d2)
test_adj

0.8555641671039261